title: André Soravassi do Carmo
Description: Portfolio with Power BI, Tableau, Salesforce, and Python achievements. Currently I work with Salesforce Development at BTG Pactual.
show_downloads: False
google_analytics: UA-180242304-1
theme: jekyll-theme-slate

